// Seed catalog. Facts (title, year, runtime, director, cast, certification) plus short original synopses.
// `stream` = Internet Archive identifier for public-domain / open-licensed films that can legally play in Moviq.
// Run `npm run sync:tmdb` with a TMDB key to add real posters, backdrops, trailers and where-to-watch data.

const M = (title, year, runtime, genres, director, cast, cert, moods, overview, stream = null) =>
  ({ title, year, runtime, genres, director, cast, cert, moods, overview, stream });

export const movies = [
  // ── Free to stream on Moviq (public domain / Creative Commons) ──
  M('Night of the Living Dead', 1968, 96, ['Horror'], 'George A. Romero', ['Duane Jones', "Judith O'Dea", 'Karl Hardman'], 'NR', ['scary', 'dark'],
    'Strangers barricade themselves inside a Pennsylvania farmhouse as the recently dead rise and close in from every side.', 'night_of_the_living_dead_dvd'),
  M('Nosferatu', 1922, 94, ['Horror', 'Fantasy'], 'F. W. Murnau', ['Max Schreck', 'Gustav von Wangenheim', 'Greta Schröder'], 'NR', ['scary', 'dark'],
    'An estate agent travels to a remote castle to close a sale and brings something ancient and hungry back to his town.', 'Nosferatu_most_complete_version_93_mins.'),
  M('The General', 1926, 78, ['Comedy', 'Action', 'Adventure'], 'Buster Keaton', ['Buster Keaton', 'Marion Mack', 'Glen Cavender'], 'NR', ['funny', 'action-packed'],
    'A stone-faced train engineer chases his stolen locomotive across enemy lines in a run of stunts that still look impossible.', 'The_General_Buster_Keaton'),
  M('Sherlock Jr.', 1924, 45, ['Comedy'], 'Buster Keaton', ['Buster Keaton', 'Kathryn McGuire', 'Joe Keaton'], 'NR', ['funny', 'mind-bending'],
    'A projectionist who dreams of being a detective falls asleep on the job and walks straight into the movie on screen.', 'sherlockjr1924_201909'),
  M('Metropolis', 1927, 148, ['Sci-Fi', 'Drama'], 'Fritz Lang', ['Brigitte Helm', 'Gustav Fröhlich', 'Alfred Abel'], 'NR', ['epic', 'mind-bending'],
    'In a towering city split between pleasure gardens above and grinding machines below, a rich son crosses the line between the two.', 'Metropolis1927EnglishVersion'),
  M('His Girl Friday', 1940, 92, ['Comedy', 'Romance'], 'Howard Hawks', ['Cary Grant', 'Rosalind Russell', 'Ralph Bellamy'], 'NR', ['funny', 'romantic'],
    'A newspaper editor has one day to stop his star reporter, and ex-wife, from quitting and remarrying. The dialogue never stops for breath.', 'his_girl_friday'),
  M('Detour', 1945, 67, ['Crime', 'Drama'], 'Edgar G. Ulmer', ['Tom Neal', 'Ann Savage', 'Claudia Drake'], 'NR', ['dark'],
    'A nightclub pianist hitchhiking west makes one bad decision, then another, on a road that only leads downhill.', 'Detour'),
  M('The Little Shop of Horrors', 1960, 72, ['Comedy', 'Horror'], 'Roger Corman', ['Jonathan Haze', 'Jackie Joseph', 'Jack Nicholson'], 'NR', ['funny'],
    'A clumsy flower-shop clerk raises a strange plant that makes him famous and demands to be fed something other than water.', 'TheLittleShopOfHorrors1960_765'),
  M('Big Buck Bunny', 2008, 10, ['Animation', 'Comedy', 'Family'], 'Sacha Goedegebure', [], 'G', ['funny', 'feel-good'],
    'A gentle giant rabbit takes cartoonish revenge on three bullying rodents. A Blender Foundation open movie.', 'BigBuckBunny_124'),
  M('Sintel', 2010, 15, ['Animation', 'Fantasy', 'Adventure'], 'Colin Levy', ['Halina Reijn', 'Thom Hoffman'], 'PG', ['emotional', 'epic'],
    'A lone traveller searches a frozen world for the baby dragon she raised. A Blender Foundation open movie.', 'Sintel'),

  // ── Catalog ──
  M('The Shawshank Redemption', 1994, 142, ['Drama'], 'Frank Darabont', ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton'], 'R', ['emotional', 'inspiring'],
    'A banker serving a life sentence spends two decades inside a brutal prison, holding on to patience and a friendship that outlasts the walls.'),
  M('The Godfather', 1972, 175, ['Crime', 'Drama'], 'Francis Ford Coppola', ['Marlon Brando', 'Al Pacino', 'James Caan'], 'R', ['dark', 'epic'],
    'The youngest son of a New York crime family wants no part of the business, until the business comes for his father.'),
  M('The Dark Knight', 2008, 152, ['Action', 'Crime', 'Drama'], 'Christopher Nolan', ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart'], 'PG-13', ['thrilling', 'dark', 'action-packed'],
    'Gotham finally has hope, then a grinning anarchist arrives to prove that anyone can be pushed past their limits.'),
  M('Pulp Fiction', 1994, 154, ['Crime', 'Drama'], 'Quentin Tarantino', ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson'], 'R', ['dark', 'funny'],
    'Hitmen, a boxer, a gangster’s wife and two diner robbers cross paths in Los Angeles, told out of order and full of talk.'),
  M('Inception', 2010, 148, ['Action', 'Sci-Fi', 'Thriller'], 'Christopher Nolan', ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page'], 'PG-13', ['mind-bending', 'thrilling'],
    'A thief who steals secrets from dreams takes one last job: planting an idea instead of taking one.'),
  M('Interstellar', 2014, 169, ['Sci-Fi', 'Drama', 'Adventure'], 'Christopher Nolan', ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain'], 'PG-13', ['epic', 'emotional', 'mind-bending'],
    'With crops failing on Earth, a former pilot leaves his children behind to search for a new home beyond a wormhole.'),
  M('Parasite', 2019, 132, ['Thriller', 'Drama', 'Comedy'], 'Bong Joon Ho', ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong'], 'R', ['dark', 'thrilling'],
    'A struggling family talks its way, one job at a time, into the household of a wealthy one.'),
  M('Spirited Away', 2001, 125, ['Animation', 'Fantasy', 'Family'], 'Hayao Miyazaki', ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki'], 'PG', ['feel-good', 'epic', 'cozy'],
    'A sulky ten-year-old stumbles into a bathhouse for spirits and must work there to free her parents from a spell.'),
  M('Whiplash', 2014, 107, ['Drama', 'Music'], 'Damien Chazelle', ['Miles Teller', 'J.K. Simmons', 'Paul Reiser'], 'R', ['thrilling', 'inspiring'],
    'A young jazz drummer earns a place in an elite band led by a conductor who believes cruelty makes greatness.'),
  M('La La Land', 2016, 128, ['Romance', 'Music', 'Drama'], 'Damien Chazelle', ['Ryan Gosling', 'Emma Stone', 'John Legend'], 'PG-13', ['romantic', 'emotional'],
    'An actress and a jazz pianist fall for each other in Los Angeles while chasing dreams that pull in different directions.'),
  M('Arrival', 2016, 116, ['Sci-Fi', 'Drama'], 'Denis Villeneuve', ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker'], 'PG-13', ['mind-bending', 'emotional'],
    'When twelve vessels settle around the globe, a linguist is asked to learn how the visitors speak before the world panics.'),
  M('Blade Runner 2049', 2017, 164, ['Sci-Fi', 'Drama'], 'Denis Villeneuve', ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas'], 'R', ['epic', 'dark'],
    'A replicant hunter uncovers a buried secret that could upend the line between people and the ones they built.'),
  M('Dune', 2021, 155, ['Sci-Fi', 'Adventure'], 'Denis Villeneuve', ['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac'], 'PG-13', ['epic'],
    'A noble family takes charge of a desert planet that holds the universe’s most precious resource and its deadliest politics.'),
  M('Dune: Part Two', 2024, 166, ['Sci-Fi', 'Adventure', 'Action'], 'Denis Villeneuve', ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson'], 'PG-13', ['epic', 'action-packed'],
    'Living among the desert people, a young exile wrestles with a prophecy that could make him a saviour or a catastrophe.'),
  M('Everything Everywhere All at Once', 2022, 139, ['Sci-Fi', 'Comedy', 'Action'], 'Daniel Kwan & Daniel Scheinert', ['Michelle Yeoh', 'Ke Huy Quan', 'Jamie Lee Curtis'], 'R', ['mind-bending', 'funny', 'emotional'],
    'A laundromat owner in the middle of a tax audit discovers she can borrow skills from every other version of herself.'),
  M('Get Out', 2017, 104, ['Horror', 'Thriller'], 'Jordan Peele', ['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford'], 'R', ['scary', 'thrilling'],
    'A weekend meeting his girlfriend’s parents starts polite and becomes stranger with every smile.'),
  M('Hereditary', 2018, 127, ['Horror', 'Drama'], 'Ari Aster', ['Toni Collette', 'Alex Wolff', 'Milly Shapiro'], 'R', ['scary', 'dark'],
    'After the family matriarch dies, grief in the house curdles into something far older and more deliberate.'),
  M('The Grand Budapest Hotel', 2014, 99, ['Comedy', 'Adventure'], 'Wes Anderson', ['Ralph Fiennes', 'Tony Revolori', 'Saoirse Ronan'], 'R', ['funny', 'cozy'],
    'A fastidious concierge and his lobby boy are framed for murder over a priceless painting in a pastel European republic.'),
  M('Paddington 2', 2017, 103, ['Family', 'Comedy', 'Adventure'], 'Paul King', ['Ben Whishaw', 'Hugh Grant', 'Sally Hawkins'], 'PG', ['feel-good', 'funny', 'cozy'],
    'A polite bear takes odd jobs to buy his aunt a pop-up book, then gets blamed when a vain actor steals it.'),
  M('Mad Max: Fury Road', 2015, 120, ['Action', 'Adventure', 'Sci-Fi'], 'George Miller', ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult'], 'R', ['action-packed', 'thrilling'],
    'A rebel driver smuggles five women out of a desert tyrant’s citadel, and the chase barely stops for two hours.'),
  M('The Matrix', 1999, 136, ['Action', 'Sci-Fi'], 'Lana Wachowski & Lilly Wachowski', ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss'], 'R', ['mind-bending', 'action-packed'],
    'A hacker is offered the truth about the world he lives in and has to choose whether he actually wants it.'),
  M('Spider-Man: Into the Spider-Verse', 2018, 117, ['Animation', 'Action', 'Adventure'], 'Bob Persichetti, Peter Ramsey & Rodney Rothman', ['Shameik Moore', 'Hailee Steinfeld', 'Mahershala Ali'], 'PG', ['feel-good', 'action-packed'],
    'A Brooklyn teen gets bitten, gains powers, and meets a crowd of spider-people from other dimensions who need his help.'),
  M('Toy Story', 1995, 81, ['Animation', 'Family', 'Comedy'], 'John Lasseter', ['Tom Hanks', 'Tim Allen', 'Don Rickles'], 'G', ['feel-good', 'cozy', 'funny'],
    'A cowboy doll’s place as favourite toy is threatened by a shiny space ranger who doesn’t know he is a toy.'),
  M('Up', 2009, 96, ['Animation', 'Family', 'Adventure'], 'Pete Docter', ['Ed Asner', 'Jordan Nagai', 'Christopher Plummer'], 'PG', ['emotional', 'feel-good'],
    'A widower ties thousands of balloons to his house to reach South America and finds a stowaway scout on his porch.'),
  M('Inside Out', 2015, 95, ['Animation', 'Family', 'Comedy'], 'Pete Docter', ['Amy Poehler', 'Phyllis Smith', 'Bill Hader'], 'PG', ['emotional', 'feel-good', 'funny'],
    'The emotions steering an eleven-year-old’s mind lose control when her family moves to a new city.'),
  M('Coco', 2017, 105, ['Animation', 'Family', 'Music'], 'Lee Unkrich', ['Anthony Gonzalez', 'Gael García Bernal', 'Benjamin Bratt'], 'PG', ['emotional', 'feel-good'],
    'A boy banned from playing music crosses into the Land of the Dead on the Day of the Dead to find his idol.'),
  M('WALL·E', 2008, 98, ['Animation', 'Sci-Fi', 'Family'], 'Andrew Stanton', ['Ben Burtt', 'Elissa Knight', 'Jeff Garlin'], 'G', ['feel-good', 'romantic'],
    'The last cleanup robot on an abandoned Earth falls for a sleek probe and follows her to the stars.'),
  M('Your Name', 2016, 106, ['Animation', 'Romance', 'Fantasy'], 'Makoto Shinkai', ['Ryunosuke Kamiki', 'Mone Kamishiraishi', 'Masami Nagasawa'], 'PG', ['romantic', 'emotional', 'mind-bending'],
    'A Tokyo boy and a country girl start waking up in each other’s bodies, and then the swaps suddenly stop.'),
  M('Before Sunrise', 1995, 101, ['Romance', 'Drama'], 'Richard Linklater', ['Ethan Hawke', 'Julie Delpy', 'Andrea Eckert'], 'R', ['romantic', 'cozy'],
    'Two strangers meet on a train and spend a single night walking and talking through Vienna.'),
  M('Eternal Sunshine of the Spotless Mind', 2004, 108, ['Romance', 'Sci-Fi', 'Drama'], 'Michel Gondry', ['Jim Carrey', 'Kate Winslet', 'Kirsten Dunst'], 'R', ['romantic', 'mind-bending', 'emotional'],
    'After a painful breakup, a man pays to have his ex erased from his memory and changes his mind halfway through.'),
  M('Pride & Prejudice', 2005, 129, ['Romance', 'Drama'], 'Joe Wright', ['Keira Knightley', 'Matthew Macfadyen', 'Brenda Blethyn'], 'PG', ['romantic', 'cozy'],
    'A sharp-tongued daughter of a family with five unmarried girls clashes with a proud and wealthy gentleman.'),
  M('Amélie', 2001, 122, ['Comedy', 'Romance'], 'Jean-Pierre Jeunet', ['Audrey Tautou', 'Mathieu Kassovitz', 'Rufus'], 'R', ['feel-good', 'romantic', 'cozy'],
    'A shy Parisian waitress secretly rearranges the lives of the people around her while avoiding her own.'),
  M('Knives Out', 2019, 130, ['Mystery', 'Comedy', 'Crime'], 'Rian Johnson', ['Daniel Craig', 'Ana de Armas', 'Chris Evans'], 'PG-13', ['funny', 'thrilling'],
    'A famous crime novelist dies after his birthday party and a southern detective questions a family that all wanted his money.'),
  M('Gone Girl', 2014, 149, ['Thriller', 'Mystery', 'Drama'], 'David Fincher', ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris'], 'R', ['dark', 'thrilling'],
    'On their fifth anniversary, a man’s wife vanishes and the media decides he must know why.'),
  M('Se7en', 1995, 127, ['Crime', 'Thriller', 'Mystery'], 'David Fincher', ['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltrow'], 'R', ['dark', 'thrilling'],
    'A retiring detective and his hot-headed replacement hunt a killer staging murders around the seven deadly sins.'),
  M('Fight Club', 1999, 139, ['Drama', 'Thriller'], 'David Fincher', ['Brad Pitt', 'Edward Norton', 'Helena Bonham Carter'], 'R', ['dark', 'mind-bending'],
    'An insomniac office worker meets a reckless soap salesman and they start an underground club that grows out of control.'),
  M('The Social Network', 2010, 120, ['Drama'], 'David Fincher', ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake'], 'PG-13', ['thrilling', 'inspiring'],
    'A Harvard student builds a website in his dorm room and ends up in two lawsuits with the people who helped him.'),
  M('Zodiac', 2007, 157, ['Crime', 'Mystery', 'Thriller'], 'David Fincher', ['Jake Gyllenhaal', 'Mark Ruffalo', 'Robert Downey Jr.'], 'R', ['dark', 'thrilling'],
    'A newspaper cartoonist becomes obsessed with the coded letters of a serial killer who is never caught.'),
  M('The Silence of the Lambs', 1991, 118, ['Thriller', 'Crime', 'Horror'], 'Jonathan Demme', ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn'], 'R', ['dark', 'scary', 'thrilling'],
    'An FBI trainee seeks help from an imprisoned, brilliant psychiatrist to catch another killer.'),
  M('Shutter Island', 2010, 138, ['Thriller', 'Mystery'], 'Martin Scorsese', ['Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley'], 'R', ['mind-bending', 'dark'],
    'Two US marshals investigate a missing patient at an island hospital for the criminally insane as a storm cuts them off.'),
  M('Goodfellas', 1990, 146, ['Crime', 'Drama'], 'Martin Scorsese', ['Robert De Niro', 'Ray Liotta', 'Joe Pesci'], 'R', ['dark'],
    'A kid from Brooklyn grows up wanting to be a gangster and gets three decades of the life, good and very bad.'),
  M('The Departed', 2006, 151, ['Crime', 'Thriller'], 'Martin Scorsese', ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson'], 'R', ['thrilling', 'dark'],
    'An undercover cop inside the Boston mob and a mob mole inside the police race to expose each other.'),
  M('The Wolf of Wall Street', 2013, 180, ['Comedy', 'Crime', 'Drama'], 'Martin Scorsese', ['Leonardo DiCaprio', 'Jonah Hill', 'Margot Robbie'], 'R', ['funny'],
    'A penny-stock broker builds a firm on fraud and excess and keeps spending as the authorities close in.'),
  M('Oppenheimer', 2023, 180, ['Drama', 'History'], 'Christopher Nolan', ['Cillian Murphy', 'Emily Blunt', 'Robert Downey Jr.'], 'R', ['epic', 'thrilling'],
    'The physicist who led the race to build the atomic bomb faces the consequences of what he made.'),
  M('The Prestige', 2006, 130, ['Mystery', 'Thriller', 'Drama'], 'Christopher Nolan', ['Hugh Jackman', 'Christian Bale', 'Scarlett Johansson'], 'PG-13', ['mind-bending', 'dark'],
    'Two stage magicians in Victorian London turn a professional rivalry into a lifelong obsession.'),
  M('Memento', 2000, 113, ['Mystery', 'Thriller'], 'Christopher Nolan', ['Guy Pearce', 'Carrie-Anne Moss', 'Joe Pantoliano'], 'R', ['mind-bending'],
    'A man who can’t form new memories hunts his wife’s killer using tattoos, notes and instant photos.'),
  M('Barbie', 2023, 114, ['Comedy', 'Fantasy'], 'Greta Gerwig', ['Margot Robbie', 'Ryan Gosling', 'America Ferrera'], 'PG-13', ['funny', 'feel-good'],
    'A perfect doll starts having imperfect thoughts and travels to the real world to find out why.'),
  M('Lady Bird', 2017, 94, ['Comedy', 'Drama'], 'Greta Gerwig', ['Saoirse Ronan', 'Laurie Metcalf', 'Tracy Letts'], 'R', ['emotional', 'funny'],
    'A Sacramento teenager spends her final year of high school fighting with her mother and dreaming of leaving.'),
  M('Little Women', 2019, 135, ['Drama', 'Romance'], 'Greta Gerwig', ['Saoirse Ronan', 'Emma Watson', 'Florence Pugh'], 'PG', ['cozy', 'emotional'],
    'Four sisters grow up during and after the American Civil War, each with her own idea of a good life.'),
  M('Past Lives', 2023, 106, ['Romance', 'Drama'], 'Celine Song', ['Greta Lee', 'Teo Yoo', 'John Magaro'], 'PG-13', ['romantic', 'emotional'],
    'Childhood friends separated when one family emigrates from Seoul meet again in New York twenty years later.'),
  M('Aftersun', 2022, 102, ['Drama'], 'Charlotte Wells', ['Paul Mescal', 'Frankie Corio', 'Celia Rowlson-Hall'], 'R', ['emotional'],
    'A woman revisits old camcorder footage of a holiday in Turkey with her young father.'),
  M('Moonlight', 2016, 111, ['Drama'], 'Barry Jenkins', ['Trevante Rhodes', 'Mahershala Ali', 'Naomie Harris'], 'R', ['emotional'],
    'Three chapters in the life of a quiet young man growing up in Miami and learning who he is.'),
  M('Portrait of a Lady on Fire', 2019, 122, ['Romance', 'Drama', 'History'], 'Céline Sciamma', ['Noémie Merlant', 'Adèle Haenel', 'Luàna Bajrami'], 'R', ['romantic', 'emotional'],
    'A painter is sent to a remote island to secretly paint a wedding portrait of a woman who refuses to pose.'),
  M('In the Mood for Love', 2000, 98, ['Romance', 'Drama'], 'Wong Kar-wai', ['Tony Leung', 'Maggie Cheung', 'Rebecca Pan'], 'PG', ['romantic', 'emotional'],
    'Two neighbours in 1960s Hong Kong suspect their spouses are having an affair and grow close themselves.'),
  M('Chungking Express', 1994, 102, ['Romance', 'Comedy', 'Drama'], 'Wong Kar-wai', ['Brigitte Lin', 'Takeshi Kaneshiro', 'Faye Wong'], 'PG-13', ['romantic', 'cozy'],
    'Two lovesick Hong Kong cops, two very different women and one late-night snack bar.'),
  M('Oldboy', 2003, 120, ['Thriller', 'Mystery', 'Action'], 'Park Chan-wook', ['Choi Min-sik', 'Yoo Ji-tae', 'Kang Hye-jung'], 'R', ['dark', 'thrilling'],
    'A man is locked in a room for fifteen years without explanation, then released and given five days to learn why.'),
  M('Train to Busan', 2016, 118, ['Horror', 'Action', 'Thriller'], 'Yeon Sang-ho', ['Gong Yoo', 'Ma Dong-seok', 'Jung Yu-mi'], 'R', ['scary', 'thrilling', 'emotional'],
    'A workaholic father and his daughter board a high-speed train just as a violent outbreak spreads across Korea.'),
  M('Seven Samurai', 1954, 207, ['Action', 'Drama', 'Adventure'], 'Akira Kurosawa', ['Toshiro Mifune', 'Takashi Shimura', 'Keiko Tsushima'], 'NR', ['epic'],
    'A farming village hires seven masterless samurai to defend it from bandits who return every harvest.'),
  M('Princess Mononoke', 1997, 134, ['Animation', 'Fantasy', 'Adventure'], 'Hayao Miyazaki', ['Yōji Matsuda', 'Yuriko Ishida', 'Yūko Tanaka'], 'PG-13', ['epic'],
    'A cursed prince travels west and lands in a war between an ironworks town and the forest gods it is cutting down.'),
  M('My Neighbor Totoro', 1988, 86, ['Animation', 'Family', 'Fantasy'], 'Hayao Miyazaki', ['Noriko Hidaka', 'Chika Sakamoto', 'Shigesato Itoi'], 'G', ['cozy', 'feel-good'],
    'Two sisters move to the countryside and befriend the big, sleepy forest spirit living in the camphor tree.'),
  M('The Lord of the Rings: The Fellowship of the Ring', 2001, 178, ['Fantasy', 'Adventure'], 'Peter Jackson', ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'], 'PG-13', ['epic'],
    'A hobbit inherits a ring of terrible power and sets out with eight companions to destroy it.'),
  M('The Lord of the Rings: The Return of the King', 2003, 201, ['Fantasy', 'Adventure'], 'Peter Jackson', ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen'], 'PG-13', ['epic', 'emotional'],
    'As armies gather for the final battle for Middle-earth, two hobbits climb toward the fire where it all began.'),
  M('Star Wars', 1977, 121, ['Sci-Fi', 'Adventure', 'Action'], 'George Lucas', ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'], 'PG', ['epic', 'feel-good'],
    'A farm boy on a desert planet joins a smuggler and an old knight to rescue a rebel princess.'),
  M('The Empire Strikes Back', 1980, 124, ['Sci-Fi', 'Adventure', 'Action'], 'Irvin Kershner', ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher'], 'PG', ['epic'],
    'The rebels scatter across the galaxy while a young pilot trains in a swamp with an unlikely teacher.'),
  M('Jurassic Park', 1993, 127, ['Adventure', 'Sci-Fi', 'Thriller'], 'Steven Spielberg', ['Sam Neill', 'Laura Dern', 'Jeff Goldblum'], 'PG-13', ['thrilling', 'epic'],
    'Scientists tour an island theme park of cloned dinosaurs the weekend its security systems fail.'),
  M('Back to the Future', 1985, 116, ['Adventure', 'Comedy', 'Sci-Fi'], 'Robert Zemeckis', ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson'], 'PG', ['feel-good', 'funny'],
    'A teenager accidentally drives a time machine to 1955 and has to make sure his parents still fall in love.'),
  M('Raiders of the Lost Ark', 1981, 115, ['Adventure', 'Action'], 'Steven Spielberg', ['Harrison Ford', 'Karen Allen', 'Paul Freeman'], 'PG', ['action-packed', 'feel-good'],
    'An archaeologist with a bullwhip races rival treasure hunters to a legendary relic.'),
  M('Jaws', 1975, 124, ['Thriller', 'Horror', 'Adventure'], 'Steven Spielberg', ['Roy Scheider', 'Robert Shaw', 'Richard Dreyfuss'], 'PG', ['thrilling', 'scary'],
    'A beach town’s police chief, a shark scientist and a salty fisherman go after a great white.'),
  M('Alien', 1979, 117, ['Horror', 'Sci-Fi'], 'Ridley Scott', ['Sigourney Weaver', 'Tom Skerritt', 'John Hurt'], 'R', ['scary', 'thrilling'],
    'The crew of a mining ship answers a distress call and brings something back on board.'),
  M('The Shining', 1980, 146, ['Horror'], 'Stanley Kubrick', ['Jack Nicholson', 'Shelley Duvall', 'Danny Lloyd'], 'R', ['scary', 'dark'],
    'A writer takes a winter caretaker job at an empty mountain hotel with his wife and son.'),
  M('2001: A Space Odyssey', 1968, 149, ['Sci-Fi', 'Adventure'], 'Stanley Kubrick', ['Keir Dullea', 'Gary Lockwood', 'William Sylvester'], 'G', ['mind-bending', 'epic'],
    'From the dawn of humankind to a mission toward Jupiter, a mysterious black monolith marks each leap forward.'),
  M('A Quiet Place', 2018, 90, ['Horror', 'Sci-Fi', 'Thriller'], 'John Krasinski', ['Emily Blunt', 'John Krasinski', 'Millicent Simmonds'], 'PG-13', ['scary', 'thrilling'],
    'A family survives on a farm in total silence, because the creatures outside hunt by sound.'),
  M('The Conjuring', 2013, 112, ['Horror'], 'James Wan', ['Vera Farmiga', 'Patrick Wilson', 'Lili Taylor'], 'R', ['scary'],
    'Two paranormal investigators help a family whose new farmhouse is not as empty as it looks.'),
  M('Us', 2019, 116, ['Horror', 'Thriller'], 'Jordan Peele', ["Lupita Nyong'o", 'Winston Duke', 'Elisabeth Moss'], 'R', ['scary', 'mind-bending'],
    'A family’s beach vacation is interrupted by four strangers standing in the driveway who look exactly like them.'),
  M('Superbad', 2007, 113, ['Comedy'], 'Greg Mottola', ['Jonah Hill', 'Michael Cera', 'Christopher Mintz-Plasse'], 'R', ['funny'],
    'Two best friends about to split up for college try to make their last high-school party count.'),
  M('The Nice Guys', 2016, 116, ['Action', 'Comedy', 'Crime'], 'Shane Black', ['Russell Crowe', 'Ryan Gosling', 'Angourie Rice'], 'R', ['funny', 'action-packed'],
    'A hired enforcer and a hapless private eye team up in 1977 Los Angeles to find a missing girl.'),
  M('Hot Fuzz', 2007, 121, ['Action', 'Comedy', 'Crime'], 'Edgar Wright', ['Simon Pegg', 'Nick Frost', 'Martin Freeman'], 'R', ['funny', 'action-packed'],
    'London’s top cop is transferred to a sleepy village where the accidents are a little too frequent.'),
  M('Baby Driver', 2017, 113, ['Action', 'Crime', 'Music'], 'Edgar Wright', ['Ansel Elgort', 'Lily James', 'Jon Hamm'], 'R', ['action-packed', 'thrilling'],
    'A young getaway driver who times every job to his playlist wants out after meeting a waitress.'),
  M('The Truman Show', 1998, 103, ['Comedy', 'Drama', 'Sci-Fi'], 'Peter Weir', ['Jim Carrey', 'Laura Linney', 'Ed Harris'], 'PG', ['mind-bending', 'feel-good'],
    'An insurance salesman starts noticing that his cheerful seaside hometown is a little too perfect.'),
  M('Forrest Gump', 1994, 142, ['Drama', 'Romance', 'Comedy'], 'Robert Zemeckis', ['Tom Hanks', 'Robin Wright', 'Gary Sinise'], 'PG-13', ['emotional', 'feel-good'],
    'A kind man from Alabama drifts through decades of American history while waiting for the girl he loves.'),
  M('Good Will Hunting', 1997, 126, ['Drama'], 'Gus Van Sant', ['Matt Damon', 'Robin Williams', 'Ben Affleck'], 'R', ['emotional', 'inspiring'],
    'A janitor at MIT is a hidden maths genius, and a therapist is the only one who can get through to him.'),
  M('Dead Poets Society', 1989, 128, ['Drama'], 'Peter Weir', ['Robin Williams', 'Robert Sean Leonard', 'Ethan Hawke'], 'PG', ['inspiring', 'emotional'],
    'An English teacher at a strict boarding school urges his students to seize the day.'),
  M('The Intouchables', 2011, 112, ['Comedy', 'Drama'], 'Olivier Nakache & Éric Toledano', ['François Cluzet', 'Omar Sy', 'Anne Le Ny'], 'R', ['feel-good', 'funny'],
    'A wealthy man paralysed in an accident hires a carefree young man from the suburbs as his caregiver.'),
  M('Top Gun: Maverick', 2022, 131, ['Action', 'Drama'], 'Joseph Kosinski', ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly'], 'PG-13', ['action-packed', 'feel-good'],
    'A veteran test pilot returns to train young aviators for a mission that looks impossible.'),
  M('John Wick', 2014, 101, ['Action', 'Thriller'], 'Chad Stahelski', ['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen'], 'R', ['action-packed'],
    'A retired hitman comes back for the gangster’s son who took the last gift his wife left him.'),
  M('Mission: Impossible – Fallout', 2018, 147, ['Action', 'Thriller'], 'Christopher McQuarrie', ['Tom Cruise', 'Henry Cavill', 'Rebecca Ferguson'], 'PG-13', ['action-packed', 'thrilling'],
    'After a mission goes wrong, a spy and his team race to recover stolen plutonium.'),
  M('Gladiator', 2000, 155, ['Action', 'Drama', 'Adventure'], 'Ridley Scott', ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen'], 'R', ['epic', 'action-packed'],
    'A betrayed Roman general is sold into slavery and fights his way through the arena toward the emperor.'),
  M('The Martian', 2015, 144, ['Sci-Fi', 'Adventure', 'Drama'], 'Ridley Scott', ['Matt Damon', 'Jessica Chastain', 'Kristen Wiig'], 'PG-13', ['inspiring', 'funny', 'feel-good'],
    'An astronaut stranded on Mars has to grow food and science his way home.'),
  M('Her', 2013, 126, ['Romance', 'Sci-Fi', 'Drama'], 'Spike Jonze', ['Joaquin Phoenix', 'Scarlett Johansson', 'Amy Adams'], 'R', ['romantic', 'emotional'],
    'A lonely letter writer falls in love with his computer’s new operating system.'),
  M('Ex Machina', 2014, 108, ['Sci-Fi', 'Thriller', 'Drama'], 'Alex Garland', ['Domhnall Gleeson', 'Alicia Vikander', 'Oscar Isaac'], 'R', ['mind-bending', 'dark'],
    'A programmer is invited to a tech CEO’s remote home to test whether his humanoid robot is truly conscious.'),
  M('Drive', 2011, 100, ['Crime', 'Drama', 'Thriller'], 'Nicolas Winding Refn', ['Ryan Gosling', 'Carey Mulligan', 'Bryan Cranston'], 'R', ['dark', 'thrilling'],
    'A quiet stunt driver who moonlights as a getaway wheelman gets involved with his neighbour and her troubles.'),
  M('No Country for Old Men', 2007, 122, ['Crime', 'Thriller'], 'Joel Coen & Ethan Coen', ['Tommy Lee Jones', 'Javier Bardem', 'Josh Brolin'], 'R', ['dark', 'thrilling'],
    'A hunter finds a case of drug money in the Texas desert and is followed by a killer who can’t be reasoned with.'),
  M('The Big Lebowski', 1998, 117, ['Comedy', 'Crime'], 'Joel Coen & Ethan Coen', ['Jeff Bridges', 'John Goodman', 'Julianne Moore'], 'R', ['funny', 'cozy'],
    'A laid-back bowler is mistaken for a millionaire with the same name and only wants his rug back.'),
  M('Fargo', 1996, 98, ['Crime', 'Thriller', 'Comedy'], 'Joel Coen & Ethan Coen', ['Frances McDormand', 'William H. Macy', 'Steve Buscemi'], 'R', ['dark', 'funny'],
    'A car salesman in debt arranges his wife’s kidnapping, and a very pregnant police chief starts asking questions.'),
  M('Prisoners', 2013, 153, ['Thriller', 'Crime', 'Drama'], 'Denis Villeneuve', ['Hugh Jackman', 'Jake Gyllenhaal', 'Viola Davis'], 'R', ['dark', 'thrilling'],
    'When his daughter goes missing on Thanksgiving, a father decides to take matters into his own hands.'),
  M('Sicario', 2015, 121, ['Crime', 'Thriller', 'Action'], 'Denis Villeneuve', ['Emily Blunt', 'Benicio del Toro', 'Josh Brolin'], 'R', ['dark', 'thrilling'],
    'An idealistic FBI agent joins a shadowy task force fighting the drug war along the US-Mexico border.'),
  M('Heat', 1995, 170, ['Crime', 'Action', 'Thriller'], 'Michael Mann', ['Al Pacino', 'Robert De Niro', 'Val Kilmer'], 'R', ['thrilling', 'epic'],
    'A meticulous thief and the obsessive detective chasing him circle each other across Los Angeles.'),
  M('The Iron Giant', 1999, 86, ['Animation', 'Family', 'Sci-Fi'], 'Brad Bird', ['Eli Marienthal', 'Jennifer Aniston', 'Vin Diesel'], 'PG', ['emotional', 'feel-good'],
    'A boy in 1957 Maine befriends a giant metal robot that fell from the sky, while a government agent hunts it.'),
  M('Ratatouille', 2007, 111, ['Animation', 'Family', 'Comedy'], 'Brad Bird', ['Patton Oswalt', 'Lou Romano', 'Brad Garrett'], 'G', ['feel-good', 'cozy'],
    'A rat with a gift for cooking teams up with a clumsy kitchen boy at a famous Paris restaurant.'),
  M('Soul', 2020, 100, ['Animation', 'Family', 'Music'], 'Pete Docter', ['Jamie Foxx', 'Tina Fey', 'Graham Norton'], 'PG', ['emotional', 'inspiring'],
    'A music teacher about to get his big break ends up in the realm where souls get their personalities.'),
  M('Poor Things', 2023, 141, ['Comedy', 'Sci-Fi', 'Romance'], 'Yorgos Lanthimos', ['Emma Stone', 'Mark Ruffalo', 'Willem Dafoe'], 'R', ['funny', 'mind-bending'],
    'A woman brought back to life by an eccentric surgeon runs off to see the world on her own terms.'),
  M('The Holdovers', 2023, 133, ['Comedy', 'Drama'], 'Alexander Payne', ['Paul Giamatti', "Da'Vine Joy Randolph", 'Dominic Sessa'], 'R', ['cozy', 'emotional', 'funny'],
    'A grumpy teacher, a troubled student and a grieving cook are stuck together at a boarding school over Christmas.'),
  M('Anatomy of a Fall', 2023, 151, ['Drama', 'Mystery', 'Thriller'], 'Justine Triet', ['Sandra Hüller', 'Swann Arlaud', 'Milo Machado-Graner'], 'R', ['thrilling', 'dark'],
    'A novelist goes on trial after her husband is found dead outside their chalet, and their son is the only witness.'),
  M('When Harry Met Sally...', 1989, 96, ['Romance', 'Comedy'], 'Rob Reiner', ['Billy Crystal', 'Meg Ryan', 'Carrie Fisher'], 'R', ['romantic', 'funny', 'cozy'],
    'Two New Yorkers spend twelve years arguing about whether men and women can ever just be friends.'),
  M('The Princess Bride', 1987, 98, ['Adventure', 'Comedy', 'Fantasy'], 'Rob Reiner', ['Cary Elwes', 'Robin Wright', 'Mandy Patinkin'], 'PG', ['feel-good', 'funny', 'romantic'],
    'A grandfather reads his sick grandson a tale of pirates, giants, sword fights and true love.'),
  M('Mean Girls', 2004, 97, ['Comedy'], 'Mark Waters', ['Lindsay Lohan', 'Rachel McAdams', 'Tina Fey'], 'PG-13', ['funny'],
    'A teen raised in Africa starts at an American high school and gets pulled into its most exclusive clique.'),
  M('RRR', 2022, 187, ['Action', 'Drama'], 'S. S. Rajamouli', ['N. T. Rama Rao Jr.', 'Ram Charan', 'Alia Bhatt'], 'NR', ['epic', 'action-packed'],
    'In 1920s India, two revolutionaries on opposite sides of the law form an unbreakable friendship.'),
  M('3 Idiots', 2009, 170, ['Comedy', 'Drama'], 'Rajkumar Hirani', ['Aamir Khan', 'R. Madhavan', 'Sharman Joshi'], 'PG-13', ['funny', 'inspiring', 'feel-good'],
    'Two friends search for the brilliant, rule-breaking classmate who vanished after engineering college.'),
  M('Dangal', 2016, 161, ['Drama', 'Sport'], 'Nitesh Tiwari', ['Aamir Khan', 'Fatima Sana Shaikh', 'Sanya Malhotra'], 'NR', ['inspiring', 'emotional'],
    'A former wrestler trains his two daughters to become world-class wrestlers against their village’s expectations.'),
  M('Vikram', 2022, 174, ['Action', 'Thriller'], 'Lokesh Kanagaraj', ['Kamal Haasan', 'Vijay Sethupathi', 'Fahadh Faasil'], 'NR', ['action-packed', 'thrilling'],
    'A special agent investigates a string of masked killings and uncovers a drug war with a legend at its centre.'),
  M('Jai Bhim', 2021, 164, ['Drama', 'Crime'], 'T. J. Gnanavel', ['Suriya', 'Lijomol Jose', 'Manikandan'], 'NR', ['emotional', 'inspiring'],
    'A lawyer takes on the case of a tribal woman whose husband disappeared in police custody.'),
  M('Soorarai Pottru', 2020, 153, ['Drama'], 'Sudha Kongara', ['Suriya', 'Aparna Balamurali', 'Paresh Rawal'], 'NR', ['inspiring', 'emotional'],
    'A village schoolteacher’s son sets out to build a low-cost airline so that anyone can afford to fly.'),
];
